### ISSUE TITLE
Does iPhone 8 Plus 15.0.2 not support it now?

### ISSUE THREAD

**Issue by ZDXNY0** [pwned4ever/Freya15#4]
![image](https://github.com/pwned4ever/Freya15/assets/146837843/471e9374-4dbc-475d-b57f-a375ac169315)

**Comment by pwned4ever** [comment]
actually just added support literally in version 1.0.9-i for 8+ 15.0 -15.0.2, as the previous version -h included support for iPhone 8+ 15.1
